### ISSUE TITLE
`incubator-airflow` admin/user/create route needs to be restored.

### ISSUE THREAD

**Issue by thisisamurray** [astronomerio/astronomer#121]
Currently, navigating to /admin/users/create results in a broken page... which seems it's to force people to add users thru the appropriate methods.

Need to restore this view to inform users that adding new users is handled somewhere else as people are reporting this as an error.

**Comment by thisisamurray** [comment]
Hey guys, reassign if neither of you two can/know how to handle this.

**Comment by andscoop** [comment]
@thisisamurray Is this only affecting our fork?

**Comment by tedmiston** [comment]
Hmm, this is weird.  I'm not aware of us changing this, but it's possible.  @thisisamurray Is this issue for Legacy SaaS, Open, or EE?

**Comment by ryw** [comment]
@schnie do we maintain one official fork that will be used in EE? we should (via a plugin) remove features from airflow UI and replace with a notice on how things work in Astronomer Airflow. Then this issue should be moved to that official fork repo for execution.

**Comment by thisisamurray** [comment]
@andscoop I only noticed it affecting multiple SaaS Cloud instances and was initially reported on Slack by users on EE.

I assumed we just removed the route as user management is handled elsewhere, but am not familiar with the codebase enough to verify.

**Comment by schnie** [comment]
@ryw yea we have an official branch for EE that we build from. Seems like this is a saas issue though.

**Comment by tedmiston** [comment]
Is this still an open issue on SaaS and EE?

**Comment by ryw** [comment]
This is open issue w/ EE

```

                          ____/ (  (    )   )  \___
                         /( (  (  )   _    ))  )   )\
                       ((     (   )(    )  )   (   )  )
                     ((/  ( _(   )   (   _) ) (  () )  )
                    ( (  ( (_)   ((    (   )  .((_ ) .  )_
                   ( (  )    (      (  )    )   ) . ) (   )
                  (  (   (  (   ) (  _  ( _) ).  ) . ) ) ( )
                  ( (  (   ) (  )   (  ))     ) _)(   )  )  )
                 ( (  ( \ ) (    (_  ( ) ( )  )   ) )  )) ( )
                  (  (   (  (   (_ ( ) ( _    )  ) (  )  )   )
                 ( (  ( (  (  )     (_  )  ) )  _)   ) _( ( )
                  ((  (   )(    (     _    )   _) _(_ (  (_ )
                   (_((__(_(__(( ( ( |  ) ) ) )_))__))_)___)
                   ((__)        \\||lll|l||///          \_))
                            (   /(/ (  )  ) )\   )
                          (    ( ( ( | | ) ) )\   )
                           (   /(| / ( )) ) ) )) )
                         (     ( ((((_(|)_)))))     )
                          (      ||\(|(|)|/||     )
                        (        |(||(||)||||        )
                          (     //|/l|||)|\\ \     )
                        (/ / //  /|//||||\\  \ \  \ _)
-------------------------------------------------------------------------------
Node: native-zodiac-9551-webserver-7bc74764fd-54ksh
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask_admin/model/base.py", line 1947, in create_view
    return_url=return_url)
  File "/usr/lib/python3.6/site-packages/flask_admin/base.py", line 308, in render
    return render_template(template, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/airflow/www/templates/airflow/model_create.html", line 18, in top-level template code
    {% extends 'admin/model/create.html' %}
  File "/usr/lib/python3.6/site-packages/flask_admin/templates/bootstrap3/admin/model/create.html", line 3, in top-level template code
    {% from 'admin/lib.html' import extra with context %} {# backward compatible #}
  File "/usr/lib/python3.6/site-packages/airflow/www/templates/admin/master.html", line 18, in top-level template code
    {% extends 'admin/base.html' %}
  File "/usr/lib/python3.6/site-packages/flask_admin/templates/bootstrap3/admin/base.html", line 30, in top-level template code
    {% block page_body %}
  File "/usr/lib/python3.6/site-packages/airflow/www/templates/admin/master.html", line 104, in block "page_body"
    {% block body %}
  File "/usr/lib/python3.6/site-packages/airflow/www/templates/airflow/model_create.html", line 28, in block "body"
    {{ super() }}
  File "/usr/lib/python3.6/site-packages/flask_admin/templates/bootstrap3/admin/model/create.html", line 22, in block "body"
    {% block create_form %}
  File "/usr/lib/python3.6/site-packages/flask_admin/templates/bootstrap3/admin/model/create.html", line 23, in block "create_form"
    {{ lib.render_form(form, return_url, extra(), form_opts) }}
  File "/usr/lib/python3.6/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 202, in template
    {% call form_tag(action=action) %}
  File "/usr/lib/python3.6/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 182, in template
    {{ caller() }}
  File "/usr/lib/python3.6/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 203, in template
    {{ render_form_fields(form, form_opts=form_opts) }}
  File "/usr/lib/python3.6/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 175, in template
    {{ render_field(form, f, kwargs) }}
  File "/usr/lib/python3.6/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 130, in template
    {{ field(**kwargs)|safe }}
  File "/usr/lib/python3.6/site-packages/wtforms/fields/core.py", line 155, in __call__
    return self.meta.render_field(self, kwargs)
  File "/usr/lib/python3.6/site-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/usr/lib/python3.6/site-packages/flask_admin/form/widgets.py", line 28, in __call__
    return super(Select2Widget, self).__call__(field, **kwargs)
  File "/usr/lib/python3.6/site-packages/wtforms/widgets/core.py", line 323, in __call__
    for val, label, selected in field.iter_choices():
  File "/usr/lib/python3.6/site-packages/flask_admin/contrib/sqla/fields.py", line 169, in iter_choices
    for pk, obj in self._get_object_list():
  File "/usr/lib/python3.6/site-packages/flask_admin/contrib/sqla/fields.py", line 103, in _get_object_list
    self._object_list = [(text_type(get_pk(obj)), obj) for obj in query]
  File "/usr/lib/python3.6/site-packages/flask_admin/contrib/sqla/fields.py", line 103, in <listcomp>
    self._object_list = [(text_type(get_pk(obj)), obj) for obj in query]
  File "/usr/lib/python3.6/site-packages/flask_admin/contrib/sqla/fields.py", line 300, in get_pk_from_identity
    cls, key = identity_key(instance=obj)
ValueError: too many values to unpack (expected 2)
```

**Comment by ryw** [comment]
can you investigate @tedmiston override that view in our fork to provide friendly message

**Comment by ryw** [comment]
Issue moved to [astronomerio/incubator-airflow #27](https://github.com/astronomerio/incubator-airflow/issues/27) via [**ZenHub**](https://www.zenhub.com/)
